document.addEventListener('DOMContentLoaded', function() {
    const timezoneSelect = document.getElementById('timezone-select');

    const timezones = {
        "Pacific/Midway": "Midway",
        "Pacific/Honolulu": "Honolulu",
        "America/Juneau": "Juneau",
        "America/Los_Angeles": "Los Angeles",
        "America/Tijuana": "Tijuana",
        "America/Denver": "Denver",
        "America/Phoenix": "Phoenix",
        "America/Chihuahua": "Chihuahua",
        "America/Mazatlan": "Mazatlan",
        "America/Chicago": "Chicago",
        "America/Regina": "Regina",
        "America/Mexico_City": "Mexiko-Stadt",
        "America/Monterrey": "Monterrey",
        "America/Guatemala": "Guatemala-Stadt",
        "America/New_York": "New York",
        "America/Indianapolis": "Indianapolis",
        "America/Bogota": "Bogotá",
        "America/Lima": "Lima",
        "America/Halifax": "Halifax",
        "America/Caracas": "Caracas",
        "America/La_Paz": "La Paz",
        "America/Santiago": "Santiago",
        "America/St_Johns": "St. John’s",
        "America/Sao_Paulo": "São Paulo",
        "America/Argentina/Buenos_Aires": "Buenos Aires",
        "America/Guyana": "Guyana",
        "America/Godthab": "Godthab",
        "Atlantic/Azores": "Azoren",
        "Atlantic/Cape_Verde": "Kap Verde",
        "Europe/London": "London",
        "Europe/Lisbon": "Lissabon",
        "Africa/Casablanca": "Casablanca",
        "Africa/Monrovia": "Monrovia",
        "Europe/Amsterdam": "Amsterdam",
        "Europe/Belgrade": "Belgrad",
        "Europe/Berlin": "Berlin",
        "Europe/Bratislava": "Bratislava",
        "Europe/Brussels": "Brüssel",
        "Europe/Budapest": "Budapest",
        "Europe/Copenhagen": "Kopenhagen",
        "Europe/Dublin": "Dublin",
        "Europe/Ljubljana": "Ljubljana",
        "Europe/Madrid": "Madrid",
        "Europe/Paris": "Paris",
        "Europe/Prague": "Prag",
        "Europe/Rome": "Rom",
        "Europe/Sarajevo": "Sarajevo",
        "Europe/Skopje": "Skopje",
        "Europe/Stockholm": "Stockholm",
        "Europe/Vienna": "Wien",
        "Europe/Warsaw": "Warschau",
        "Europe/Zagreb": "Zagreb",
        "Europe/Athens": "Athen",
        "Europe/Bucharest": "Bukarest",
        "Africa/Cairo": "Kairo",
        "Africa/Harare": "Harare",
        "Europe/Helsinki": "Helsinki",
        "Europe/Istanbul": "Istanbul",
        "Asia/Jerusalem": "Jerusalem",
        "Europe/Kiev": "Kiew",
        "Europe/Minsk": "Minsk",
        "Europe/Riga": "Riga",
        "Europe/Sofia": "Sofia",
        "Europe/Tallinn": "Tallinn",
        "Europe/Vilnius": "Vilnius",
        "Asia/Baghdad": "Bagdad",
        "Asia/Kuwait": "Kuwait",
        "Africa/Nairobi": "Nairobi",
        "Asia/Riyadh": "Riad",
        "Asia/Tehran": "Teheran",
        "Asia/Muscat": "Maskat",
        "Asia/Baku": "Baku",
        "Asia/Yerevan": "Jerewan",
        "Asia/Tbilisi": "Tiflis",
        "Asia/Kabul": "Kabul",
        "Asia/Yekaterinburg": "Jekaterinburg",
        "Asia/Karachi": "Karatschi",
        "Asia/Tashkent": "Taschkent",
        "Asia/Kolkata": "Kalkutta",
        "Asia/Kathmandu": "Kathmandu",
        "Asia/Almaty": "Almaty",
        "Asia/Dhaka": "Dhaka",
        "Asia/Novosibirsk": "Nowosibirsk",
        "Asia/Bangkok": "Bangkok",
        "Asia/Jakarta": "Jakarta",
        "Asia/Krasnoyarsk": "Krasnojarsk",
        "Asia/Shanghai": "Shanghai",
        "Asia/Chongqing": "Chongqing",
        "Asia/Hong_Kong": "Hongkong",
        "Asia/Urumqi": "Urumtschi",
        "Asia/Kuala_Lumpur": "Kuala Lumpur",
        "Asia/Singapore": "Singapur",
        "Asia/Taipei": "Taipeh",
        "Australia/Perth": "Perth",
        "Asia/Irkutsk": "Irkutsk",
        "Asia/Seoul": "Seoul",
        "Asia/Tokyo": "Tokio",
        "Asia/Yakutsk": "Jakutsk",
        "Australia/Darwin": "Darwin",
        "Australia/Adelaide": "Adelaide",
        "Australia/Sydney": "Sydney",
        "Australia/Brisbane": "Brisbane",
        "Australia/Hobart": "Hobart",
        "Asia/Vladivostok": "Wladiwostok",
        "Pacific/Guam": "Guam",
        "Pacific/Port_Moresby": "Port Moresby",
        "Asia/Magadan": "Magadan",
        "Asia/Kamchatka": "Kamtschatka",
        "Pacific/Fiji": "Fidschi",
        "Pacific/Auckland": "Auckland",
        "Pacific/Tongatapu": "Tongatapu"
    };

    for (const [zone, name] of Object.entries(timezones)) {
        const option = document.createElement('option');
        option.value = zone;
        option.textContent = name; // Set city name only
        timezoneSelect.appendChild(option);
    }

    // Set default timezone to Los Angeles
    timezoneSelect.value = "America/Los_Angeles";
});